
version: '1.1b3.{build}'

environment:

  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

  matrix:
    - JOB: "2.7 32-bit"
      TOXENV: "py27"
      PYTHON: "C:\\Python27.14"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "32"

    - JOB: "2.7 64-bit"
      TOXENV: "py27"
      PYTHON: "C:\\Python27.14-x64"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "64"

init:
  - "ECHO %TOXENV%"

install:
  - echo "Downloading deps..."
  - cd C:\
  #Install Inno Setup
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\spambayes
  - "%CMD_IN_ENV% %PYTHON%\\python setup.py bdist_wininst"
